[package]
authors       = ["강동윤 <kdy1997.dev@gmail.com>"]
description   = "rust port of babel and closure compiler."
documentation = "https://rustdoc.swc.rs/swc_ecma_transforms_proposal/"
edition       = "2021"
include       = ["Cargo.toml", "src/**/*.rs"]
license       = "Apache-2.0"
name          = "swc_ecma_transforms_proposal"
repository    = "https://github.com/swc-project/swc.git"
version       = "0.166.5"

[lib]
bench = false

[features]
default      = []
multi-module = ["swc_ecma_loader"]

[dependencies]
either     = "1.6.1"
rustc-hash = "1"
serde      = { version = "1.0.118", features = ["derive"] }
smallvec   = "1.8.0"

swc_atoms                   = { version = "0.5.9", path = "../swc_atoms" }
swc_common                  = { version = "0.32.1", path = "../swc_common" }
swc_ecma_ast                = { version = "0.109.1", path = "../swc_ecma_ast" }
swc_ecma_loader             = { version = "0.44.3", path = "../swc_ecma_loader", optional = true }
swc_ecma_transforms_base    = { version = "0.132.4", path = "../swc_ecma_transforms_base" }
swc_ecma_transforms_classes = { version = "0.121.4", path = "../swc_ecma_transforms_classes" }
swc_ecma_transforms_macros  = { version = "0.5.3", path = "../swc_ecma_transforms_macros" }
swc_ecma_utils              = { version = "0.122.1", path = "../swc_ecma_utils" }
swc_ecma_visit              = { version = "0.95.1", path = "../swc_ecma_visit" }

[dev-dependencies]
serde_json = "1.0.66"

swc_ecma_parser             = { version = "0.139.1", path = "../swc_ecma_parser" }
swc_ecma_transforms_compat  = { version = "0.158.5", path = "../swc_ecma_transforms_compat" }
swc_ecma_transforms_testing = { version = "0.135.4", path = "../swc_ecma_transforms_testing" }
testing                     = { version = "0.34.1", path = "../testing" }
